### ISSUE TITLE
Is there a plan to move to v2.2.3 ? Is this instance still maintained ?

### ISSUE THREAD

**Issue by L0wkey96** [fleischsalatinspace/pathfinder.lost-in-w.space#5]
Pretty much the title :)
Is there a plan to move to v2.2.3 ? Is this instance still maintained ?

Been using this instance for small corp without infra, it's working well so far but having back the Thera connection would be nice (the issue with the new EVE scout API have been solved in v2.2.3).

**Comment by fleischsalatinspace** [comment]
Hello @L0wkey96  ,

sorry for the late reply, i was out of office :palm_tree:  . 

Regarding your question: i think you are talking about Pathfinder version v2.2.4 ? https://github.com/goryn-clade/pathfinder/releases/tag/v2.2.4 . Because the instance `pathfinder.lost-in-w.space` is already on v2.2.3

Why is the public instance not on v2.2.4 you maybe asking? Because v2.2.4 did indeed fix the eve-scout api, but Thera routing is still broken https://github.com/goryn-clade/pathfinder/issues/221  . There is a pull request pending https://github.com/goryn-clade/pathfinder/pull/226 , but it has not been merged yet. 

Looking forward to you reply :)

**Comment by L0wkey96** [comment]
Hello @fleischsalatinspace thanks for the answer :) 

I hope you spent some good holidays, I indeed meant the v2.2.4.

I saw the issue around EVE Scout API is still open on goryn Github, 

I don't know if they wait for a rework of the module to include Turnur to close it or something else, but I can confirm to have tried it on some friends instance that the changes in the v2.2.4 solved the issue with Thera :)

**Comment by L0wkey96** [comment]
Hello @fleischsalatinspace thanks for the answer :)

I hope you spent some good holidays, I indeed meant the v2.2.4.

I used the instance of friends running the v2.2.4 and the Thera connection module was working so I assumed this version solved the issue. 
Now that you pointed out this pull not yet merged and the issue still open, that might be they used that instead.

I'll ask my friends what they did to get Thera back up and working in their PF and get back to you if you're interested.

**Comment by L0wkey96** [comment]
Answer given to me was just: update to the last version.

They just updated to latest version and Thera module has been working so far.

**Comment by fleischsalatinspace** [comment]
This instance is going to shut down on 2024-10-31. Please use https://public.eve-pathfinder.online/ as stated here https://forums.eveonline.com/t/service-lost-in-w-space-public-private-pathfinder-hosting-discontinued-as-of-2024-10-31/334504/60
thank you
